npmScopes:
  djrhails:
    npmAuthToken: "${NPM_AUTH_TOKEN:-''}"
    npmRegistryServer: "https://npm.pkg.github.com/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-sources.cjs
