npmScopes:
  djrhails:
    npmRegistryServer: "https://npm.pkg.github.com/"
    npmAuthToken: ${NPM_AUTH_TOKEN}

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.js
