name: Continuous Integration

on: push

jobs:
    build-lint-type-test:
      name: Build, Lint, Type Check and Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
            registry-url: https://npm.pkg.github.com/
        - name: Install dependencies
          run: yarn
          env:
            NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        - name: Build
          run: yarn build
        - name: Type Check
          run: yarn type
        - name: Lint Check
          run: yarn lint
        - name: Test
          run: yarn test